name: Update themes

on:
  # trigger on template changes
  push:
    paths:
      - templates/**
  # trigger on every saturday at 00:00
  schedule:
    - cron: "0 0 * * 6"
  # manual trigger
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/checkout@v4
        with:
          repository: tinted-theming/schemes
          path: schemes

      - name: Tinted Builder Rust
        uses: tinted-theming/tinted-builder-rust@v0.21.0
        with:
          path: schemes

      - name: create pull request
        run: gh pr create -B main -H auto-tinted --title 'Feat created new tinted themes' --body 'Created by Github action'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
