name: Update themes

on:
  # trigger on template changes
  push:
    paths:
      - templates/**
  # trigger on every saturday at 00:00
  schedule:
    - cron: "0 0 * * 6"
  # manual trigger
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          ref: ${{ github.head_ref }}
          # Value already defaults to true, but `persist-credentials` is required to push new commits to the repository.
          persist-credentials: true

     

      - name: Tinted Builder Rust
        uses: tinted-theming/tinted-builder-rust@v0.21.0
        with:
          path: schemes
          
      - name: "Update schemes"
        run: |
          tinted-builder-rust sync
          tinted-builder-rust build .
          
      - name: create Commit
        uses: stefanzweifel/git-auto-commit-action@v7
        with:
            commit_message: creating new schemes
